### ISSUE TITLE
Teams page: Scores and schedule

### ISSUE THREAD

**Issue by Doxterpepper** [SyngergyScheduling/Synergy_Code#28]
Page that lists all teams.
Edit: Teams page should be dynamic and pull from the database for the teams.

**Comment by Doxterpepper** [comment]
#47 , The teams page exists but needs to be more dynamic so this will stay open for now

**Comment by ohdabbs** [comment]
#50

**Comment by ohdabbs** [comment]
Still needs to list scores and schedule

**Comment by Doxterpepper** [comment]
There's always more

**Comment by ohdabbs** [comment]
Going to try and tackle this tonight.
