### ISSUE TITLE
Scoring table

### ISSUE THREAD

**Issue by Doxterpepper** [SyngergyScheduling/Synergy_Code#40]
Scoring page needs to have more options for score. drop downs for referee input and should operate on the DB.

**Comment by ohdabbs** [comment]
#49

**Comment by Doxterpepper** [comment]
This should be in the format of a table. Similar to how a rubric would be presented. It should include a Organization field, Rebuttal field, and use of facts and statistics field. Should take these tables, make one overall score out of them, and then store that score in the database.

**Comment by Doxterpepper** [comment]
#63
