### ISSUE TITLE
Distinguish between Referee and Super Referee

### ISSUE THREAD

**Issue by ohdabbs** [SyngergyScheduling/Synergy_Code#42]
Add some logic on calendar.html.erb file which only displays score buttons when
1) Date is current or past
AND
2) Super referee is logged in

OR 

1) Date is current or past
AND
2) Referee is logged in and match does not have a score

**Comment by Doxterpepper** [comment]
We should be able to access the database in the view to check what user level the user is that is loading a page.

**Comment by Doxterpepper** [comment]
Also is this a Calendar milestone or should we make a new milestone for scoring? I lean toward the latter.

**Comment by Doxterpepper** [comment]
#46 has some code for doing this but it's only in the navigation bar.

**Comment by Doxterpepper** [comment]
We have the referee logged in part, now we just need to look at the dates.

**Comment by Doxterpepper** [comment]
This is done in the DB and has been solved in the navigation html. Do what is done in the navigation page to distinguish between super referees and regular referees.
